package pojos;
// Generated 6 mar 2025, 17:05:57 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;

/**
 * Albaranes generated by hbm2java
 */
@Entity
@Table(name = "albaranes")
public class Albaranes implements java.io.Serializable {

	private static final long serialVersionUID = -103313744362316324L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int idAlbaran;

	@Enumerated(EnumType.STRING)
	@Column(name = "tipo_albaran", nullable = false, length = 100)
	private TipoAlbaran tipoAlbaran;

	@Column(name = "fecha_albaran", nullable = false)
	private Timestamp fechaAlbaran;

	@Lob
	@Column(name = "foto_albaran")
	private byte[] fotoAlbaran;

	@ManyToOne
	@JoinColumn(name = "id_proveedor", nullable = false)
	@NotNull(message = "El proveedor es obligatorio")
	private Proveedores proveedor;

	@Column(name = "fecha_creacion", nullable = false)
	private Timestamp fechaCreacion;

	@Enumerated(EnumType.STRING)
	@Column(name = "estado", length = 50)
	private EstadoAlbaran estado;

	@OneToMany(mappedBy = "albaran", cascade = CascadeType.ALL, orphanRemoval = true)
	@JsonManagedReference 
	private Set<Movimientos> movimientos = new HashSet<>();


	@OneToMany(mappedBy = "albaran", cascade = CascadeType.ALL, orphanRemoval = true)
	@JsonManagedReference
	private Set<DetallesAlbaran> detallesAlbaran = new HashSet<>();

	public enum TipoAlbaran {
		entrada, salida
	}

	public enum EstadoAlbaran {
		Pendiente, Pagado, Cancelado
	}

	public Albaranes() {
	}

	public Albaranes(TipoAlbaran tipoAlbaran, Timestamp fechaAlbaran, Proveedores proveedor, Timestamp fechaCreacion) {
		this.tipoAlbaran = tipoAlbaran;
		this.fechaAlbaran = fechaAlbaran;
		this.proveedor = proveedor;
		this.fechaCreacion = fechaCreacion;
	}

	public Albaranes(TipoAlbaran tipoAlbaran, Timestamp fechaAlbaran, byte[] fotoAlbaran, Proveedores proveedor,
			Timestamp fechaCreacion, EstadoAlbaran estado, Set<Movimientos> movimientos,
			Set<DetallesAlbaran> detallesAlbaran) {
		this.tipoAlbaran = tipoAlbaran;
		this.fechaAlbaran = fechaAlbaran;
		this.fotoAlbaran = fotoAlbaran;
		this.proveedor = proveedor;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.movimientos = movimientos;
		this.detallesAlbaran = detallesAlbaran;
	}

	public Integer getIdAlbaran() {
		return idAlbaran;
	}

	public void setIdAlbaran(Integer idAlbaran) {
		this.idAlbaran = idAlbaran;
	}

	public TipoAlbaran getTipoAlbaran() {
		return tipoAlbaran;
	}

	public void setTipoAlbaran(TipoAlbaran tipoAlbaran) {
		this.tipoAlbaran = tipoAlbaran;
	}

	public Timestamp getFechaAlbaran() {
		return fechaAlbaran;
	}

	public void setFechaAlbaran(Timestamp fechaAlbaran) {
		this.fechaAlbaran = fechaAlbaran;
	}

	public byte[] getFotoAlbaran() {
		return fotoAlbaran;
	}

	public void setFotoAlbaran(byte[] fotoAlbaran) {
		this.fotoAlbaran = fotoAlbaran;
	}

	public Proveedores getProveedor() {
		return proveedor;
	}

	public void setProveedor(Proveedores proveedor) {
		this.proveedor = proveedor;
	}

	public Timestamp getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Timestamp fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public EstadoAlbaran getEstado() {
		return estado;
	}

	public void setEstado(EstadoAlbaran estado) {
		this.estado = estado;
	}

	public Set<Movimientos> getMovimientos() {
		return movimientos;
	}

	public void setMovimientos(Set<Movimientos> movimientos) {
		this.movimientos = movimientos;
	}

	public Set<DetallesAlbaran> getDetallesAlbaran() {
		return detallesAlbaran;
	}

	public void setDetallesAlbaran(Set<DetallesAlbaran> detallesAlbaran) {
		this.detallesAlbaran = detallesAlbaran;
	}

	public Set getMovimientoses() {
		return this.movimientos;
	}

	public void setMovimientoses(Set movimientoses) {
		this.movimientos = movimientoses;
	}

	public Set getDetallesAlbarans() {
		return this.detallesAlbaran;
	}

	public void setDetallesAlbarans(Set detallesAlbarans) {
		this.detallesAlbaran = detallesAlbarans;
	}

}
