package pojos;
// Generated 6 mar 2025, 17:05:57 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;

/**
 * DetallesAlbaran generated by hbm2java
 */
@Entity
@Table(name = "detalles_albaran")
public class DetallesAlbaran implements java.io.Serializable {

	private static final long serialVersionUID = 3246065114967305279L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int idDetalle;

	@ManyToOne
	@JoinColumn(name = "id_producto", nullable = false)
	@JsonBackReference
	private Productos producto;

	@ManyToOne
	@JoinColumn(name = "id_albaran", nullable = false)
	@JsonBackReference
	private Albaranes albaran;

	@Column(name = "precio_unitario", nullable = false, precision = 10, scale = 2)
	@NotNull(message = "El precio unitario es obligatorio")
	private BigDecimal precioUnitario;

	@Column(name = "cantidad", nullable = false)
	private int cantidad;

	public DetallesAlbaran() {
	}

	public DetallesAlbaran(Productos producto, Albaranes albaran, BigDecimal precioUnitario, int cantidad) {
		this.producto = producto;
		this.albaran = albaran;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
	}

	public Integer getIdDetalle() {
		return idDetalle;
	}

	public void setIdDetalle(Integer idDetalle) {
		this.idDetalle = idDetalle;
	}

	public Productos getProducto() {
		return producto;
	}

	public void setProducto(Productos producto) {
		this.producto = producto;
	}

	public Albaranes getAlbaran() {
		return albaran;
	}

	public void setAlbaran(Albaranes albaran) {
		this.albaran = albaran;
	}

	public BigDecimal getPrecioUnitario() {
		return precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	public int getCantidad() {
		return cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
}
